INSERT INTO legal_templates (id, name, description, category, subcategory, "fileType", file_size, file_url, tags, legal_area, is_default, download_count, created_at, updated_at) VALUES
(gen_random_uuid(), 'Demanda de Tutela', 'Modelo de demanda de tutela para proteccion de derechos fundamentales', 'Tutelas', 'Demandas', 'docx', 0, '/templates/default/tutela.docx', '["tutela", "derechos fundamentales"]', 'Constitucional', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Replica a Tutela', 'Modelo de replica a demanda de tutela', 'Tutelas', 'Contestaciones', 'docx', 0, '/templates/default/replica-tutela.docx', '["replica", "tutela"]', 'Constitucional', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Contrato de Prestacion de Servicios', 'Modelo de contrato de prestacion de servicios profesionales', 'Contratos', 'Servicios', 'docx', 0, '/templates/default/contrato-servicios.docx', '["contrato", "prestacion servicios"]', 'Civil', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Contrato Laboral a Termino Indefinido', 'Modelo de contrato laboral a termino indefinido', 'Contratos', 'Laboral', 'docx', 0, '/templates/default/contrato-laboral.docx', '["contrato", "laboral"]', 'Laboral', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Demanda Laboral Ordinaria', 'Modelo de demanda laboral ordinaria', 'Laboral', 'Demandas', 'docx', 0, '/templates/default/demanda-laboral.docx', '["demanda", "laboral"]', 'Laboral', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Liquidacion de Prestaciones Sociales', 'Modelo de liquidacion de prestaciones sociales', 'Laboral', 'Documentos', 'docx', 0, '/templates/default/liquidacion.docx', '["liquidacion", "prestaciones"]', 'Laboral', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Derecho de Peticion', 'Modelo de derecho de peticion general', 'Administrativo', 'Peticiones', 'docx', 0, '/templates/default/derecho-peticion.docx', '["peticion", "derecho de peticion"]', 'Administrativo', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Recurso de Reposicion', 'Modelo de recurso de reposicion en via administrativa', 'Administrativo', 'Recursos', 'docx', 0, '/templates/default/reposicion.docx', '["recurso", "reposicion"]', 'Administrativo', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Demanda de Divorcio', 'Modelo de demanda de divorcio contencioso', 'Familia', 'Demandas', 'docx', 0, '/templates/default/divorcio.docx', '["divorcio", "familia"]', 'Familia', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Demanda de Responsabilidad Civil', 'Modelo de demanda de responsabilidad civil contractual', 'Civil', 'Demandas', 'docx', 0, '/templates/default/resp-civil.docx', '["responsabilidad civil", "contractual"]', 'Civil', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Habeas Data', 'Modelo de tutela por violacion del derecho al habeas data', 'Tutelas', 'Demandas', 'docx', 0, '/templates/default/habeas-data.docx', '["habeas data", "datos personales"]', 'Constitucional', true, 0, NOW(), NOW()),
(gen_random_uuid(), 'Demanda de Nulidad y Restablecimiento', 'Modelo de demanda de nulidad y restablecimiento del derecho', 'Administrativo', 'Demandas', 'docx', 0, '/templates/default/nulidad-restablecimiento.docx', '["nulidad", "restablecimiento"]', 'Administrativo', true, 0, NOW(), NOW());
